name: Fantasy diario (Python)

on:
  schedule:
    - cron: "0 6 * * *"   # 08:00 en Madrid en verano, 07:00 en invierno
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: fantasy-daily
      cancel-in-progress: false
    env:
      TZ: Europe/Madrid
      # Ajusta estos nombres a tus secrets reales:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
      # Pon aquí cualquier otra variable que uses (API keys, etc.)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.11 + caché
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Instalar dependencias
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      # Descomenta si haces scraping con Playwright
      # - name: Playwright browsers
      #   run: |
      #     pip install playwright
      #     python -m playwright install --with-deps

      - name: Tests (opcional)
        if: hashFiles('tests/**') != ''
        run: |
          pip install pytest
          pytest -q

      - name: Ejecutar lanzador
        run: |
          set -e
          for i in 1 2 3; do
            python lanzador_fantasy_cloud.py && break || {
              echo "Intento $i fallido; reintento en 15s…"
              sleep 15
            }
          done

      - name: Subir resultados (si generas ficheros)
        if: always() && hashFiles('output/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: resultados-fantasy
          path: output/**
          if-no-files-found: ignore
